### ISSUE TITLE
Novas paginas

### ISSUE THREAD

**Issue by 404jv** [404jv/lunabus#12]
Jão R.:
- [x] ginasio cidade alta
- [x] premen II
- [x] praça matriz
- [x] pão de açucar
- [x] igreja da guaira
- [x] UEM

Ruan:
- [x] Caixa economica
- [x] Jaracatia
- [x] Pernambucanas
- [x] Posto Vitória
- [x] Acig

Jão Lima:
- [x] Bar do Zequinha
- [x] IFPR
- [x] Jardim Universitário
- [x] Oficina do Cidinho
- [x] Sicredi

**Comment by jvolima** [comment]
Loco de bão

**Comment by FixRuan** [comment]
👌

**Comment by 404jv** [comment]
- [ ] mapa trajeto 2 para Pão de Açucar e UEM

**Comment by 404jv** [comment]
são as mesmas tabelas em todos os seus pontos @FixRuan 

7:10 | 7:10 | 7:10 | 7:10 | 7:10 | 7:10
8:10 | 8:10 | 8:10 | 8:10 | 8:10 | 8:10
12:40 | 12:40 | 12:40 | 12:40 | 12:40 | XXXX
16:40 | 16:40 | 16:40 | 16:40 | 16:40 | XXXX
18:10 | 18:10 | 18:10 | 18:10 | 18:10 | XXXX
